# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: datasetV1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='datasetV1.proto',
  package='protobuffer',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x64\x61tasetV1.proto\x12\x08protobuf\" \n\rDataFrameMeta\x12\x0f\n\x07headers\x18\x01 \x03(\t\"\xd5\x01\n\x0c\x44\x61taFrameRow\x12\x33\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32$.protobuffer.DataFrameRow.DataFrameCell\x1a\x8f\x01\n\rDataFrameCell\x12\x11\n\x07int32_t\x18\x01 \x01(\x05H\x00\x12\x11\n\x07int64_t\x18\x02 \x01(\x03H\x00\x12\x12\n\x08\x64ouble_t\x18\x03 \x01(\x01H\x00\x12\x11\n\x07\x66loat_t\x18\x04 \x01(\x02H\x00\x12\x12\n\x08string_t\x18\x05 \x01(\tH\x00\x12\x10\n\x06\x62ool_t\x18\x06 \x01(\x08H\x00\x42\x0b\n\tcell_typeBG\n4de.uni_passau.fim.padas.padre.api.converter.protobufB\x0f\x44\x61tasetV1Protosb\x06proto3')
)




_DATAFRAMEMETA = _descriptor.Descriptor(
  name='DataFrameMeta',
  full_name='protobuffer.DataFrameMeta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headers', full_name='protobuffer.DataFrameMeta.headers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=61,
)


_DATAFRAMEROW_DATAFRAMECELL = _descriptor.Descriptor(
  name='DataFrameCell',
  full_name='protobuffer.DataFrameRow.DataFrameCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_t', full_name='protobuffer.DataFrameRow.DataFrameCell.int32_t', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_t', full_name='protobuffer.DataFrameRow.DataFrameCell.int64_t', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_t', full_name='protobuffer.DataFrameRow.DataFrameCell.double_t', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_t', full_name='protobuffer.DataFrameRow.DataFrameCell.float_t', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_t', full_name='protobuffer.DataFrameRow.DataFrameCell.string_t', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_t', full_name='protobuffer.DataFrameRow.DataFrameCell.bool_t', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cell_type', full_name='protobuffer.DataFrameRow.DataFrameCell.cell_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=134,
  serialized_end=277,
)

_DATAFRAMEROW = _descriptor.Descriptor(
  name='DataFrameRow',
  full_name='protobuffer.DataFrameRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cells', full_name='protobuffer.DataFrameRow.cells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAFRAMEROW_DATAFRAMECELL, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=277,
)

_DATAFRAMEROW_DATAFRAMECELL.containing_type = _DATAFRAMEROW
_DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type'].fields.append(
  _DATAFRAMEROW_DATAFRAMECELL.fields_by_name['int32_t'])
_DATAFRAMEROW_DATAFRAMECELL.fields_by_name['int32_t'].containing_oneof = _DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type']
_DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type'].fields.append(
  _DATAFRAMEROW_DATAFRAMECELL.fields_by_name['int64_t'])
_DATAFRAMEROW_DATAFRAMECELL.fields_by_name['int64_t'].containing_oneof = _DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type']
_DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type'].fields.append(
  _DATAFRAMEROW_DATAFRAMECELL.fields_by_name['double_t'])
_DATAFRAMEROW_DATAFRAMECELL.fields_by_name['double_t'].containing_oneof = _DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type']
_DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type'].fields.append(
  _DATAFRAMEROW_DATAFRAMECELL.fields_by_name['float_t'])
_DATAFRAMEROW_DATAFRAMECELL.fields_by_name['float_t'].containing_oneof = _DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type']
_DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type'].fields.append(
  _DATAFRAMEROW_DATAFRAMECELL.fields_by_name['string_t'])
_DATAFRAMEROW_DATAFRAMECELL.fields_by_name['string_t'].containing_oneof = _DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type']
_DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type'].fields.append(
  _DATAFRAMEROW_DATAFRAMECELL.fields_by_name['bool_t'])
_DATAFRAMEROW_DATAFRAMECELL.fields_by_name['bool_t'].containing_oneof = _DATAFRAMEROW_DATAFRAMECELL.oneofs_by_name['cell_type']
_DATAFRAMEROW.fields_by_name['cells'].message_type = _DATAFRAMEROW_DATAFRAMECELL
DESCRIPTOR.message_types_by_name['DataFrameMeta'] = _DATAFRAMEMETA
DESCRIPTOR.message_types_by_name['DataFrameRow'] = _DATAFRAMEROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataFrameMeta = _reflection.GeneratedProtocolMessageType('DataFrameMeta', (_message.Message,), dict(
  DESCRIPTOR = _DATAFRAMEMETA,
  __module__ = 'datasetV1_pb2'
  # @@protoc_insertion_point(class_scope:protobuffer.DataFrameMeta)
  ))
_sym_db.RegisterMessage(DataFrameMeta)

DataFrameRow = _reflection.GeneratedProtocolMessageType('DataFrameRow', (_message.Message,), dict(

  DataFrameCell = _reflection.GeneratedProtocolMessageType('DataFrameCell', (_message.Message,), dict(
    DESCRIPTOR = _DATAFRAMEROW_DATAFRAMECELL,
    __module__ = 'datasetV1_pb2'
    # @@protoc_insertion_point(class_scope:protobuffer.DataFrameRow.DataFrameCell)
    ))
  ,
  DESCRIPTOR = _DATAFRAMEROW,
  __module__ = 'datasetV1_pb2'
  # @@protoc_insertion_point(class_scope:protobuffer.DataFrameRow)
  ))
_sym_db.RegisterMessage(DataFrameRow)
_sym_db.RegisterMessage(DataFrameRow.DataFrameCell)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n4de.uni_passau.fim.padas.padre.api.converter.protobufB\017DatasetV1Protos'))
# @@protoc_insertion_point(module_scope)
