# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: genericV1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='genericV1.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=_b('\n;de.uni_passau.fim.padas.padre.api.converter.binary.protobufB\017GenericV1Protos'),
  serialized_pb=_b('\n\x0fgenericV1.proto\x12\x08protobuf\"\x17\n\x04Meta\x12\x0f\n\x07headers\x18\x01 \x03(\t\"\xc1\x01\n\x07\x44\x61taRow\x12)\n\x05\x63\x65lls\x18\x01 \x03(\x0b\x32\x1a.protobuf.DataRow.DataCell\x1a\x8a\x01\n\x08\x44\x61taCell\x12\x11\n\x07int32_t\x18\x01 \x01(\x05H\x00\x12\x11\n\x07int64_t\x18\x02 \x01(\x03H\x00\x12\x12\n\x08\x64ouble_t\x18\x03 \x01(\x01H\x00\x12\x11\n\x07\x66loat_t\x18\x04 \x01(\x02H\x00\x12\x12\n\x08string_t\x18\x05 \x01(\tH\x00\x12\x10\n\x06\x62ool_t\x18\x06 \x01(\x08H\x00\x42\x0b\n\tcell_typeBN\n;de.uni_passau.fim.padas.padre.api.converter.binary.protobufB\x0fGenericV1Protosb\x06proto3')
)




_META = _descriptor.Descriptor(
  name='Meta',
  full_name='protobuf.Meta',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='headers', full_name='protobuf.Meta.headers', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=52,
)


_DATAROW_DATACELL = _descriptor.Descriptor(
  name='DataCell',
  full_name='protobuf.DataRow.DataCell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_t', full_name='protobuf.DataRow.DataCell.int32_t', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='int64_t', full_name='protobuf.DataRow.DataCell.int64_t', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='double_t', full_name='protobuf.DataRow.DataCell.double_t', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='float_t', full_name='protobuf.DataRow.DataCell.float_t', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='string_t', full_name='protobuf.DataRow.DataCell.string_t', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bool_t', full_name='protobuf.DataRow.DataCell.bool_t', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cell_type', full_name='protobuf.DataRow.DataCell.cell_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=110,
  serialized_end=248,
)

_DATAROW = _descriptor.Descriptor(
  name='DataRow',
  full_name='protobuf.DataRow',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cells', full_name='protobuf.DataRow.cells', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DATAROW_DATACELL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=248,
)

_DATAROW_DATACELL.containing_type = _DATAROW
_DATAROW_DATACELL.oneofs_by_name['cell_type'].fields.append(
  _DATAROW_DATACELL.fields_by_name['int32_t'])
_DATAROW_DATACELL.fields_by_name['int32_t'].containing_oneof = _DATAROW_DATACELL.oneofs_by_name['cell_type']
_DATAROW_DATACELL.oneofs_by_name['cell_type'].fields.append(
  _DATAROW_DATACELL.fields_by_name['int64_t'])
_DATAROW_DATACELL.fields_by_name['int64_t'].containing_oneof = _DATAROW_DATACELL.oneofs_by_name['cell_type']
_DATAROW_DATACELL.oneofs_by_name['cell_type'].fields.append(
  _DATAROW_DATACELL.fields_by_name['double_t'])
_DATAROW_DATACELL.fields_by_name['double_t'].containing_oneof = _DATAROW_DATACELL.oneofs_by_name['cell_type']
_DATAROW_DATACELL.oneofs_by_name['cell_type'].fields.append(
  _DATAROW_DATACELL.fields_by_name['float_t'])
_DATAROW_DATACELL.fields_by_name['float_t'].containing_oneof = _DATAROW_DATACELL.oneofs_by_name['cell_type']
_DATAROW_DATACELL.oneofs_by_name['cell_type'].fields.append(
  _DATAROW_DATACELL.fields_by_name['string_t'])
_DATAROW_DATACELL.fields_by_name['string_t'].containing_oneof = _DATAROW_DATACELL.oneofs_by_name['cell_type']
_DATAROW_DATACELL.oneofs_by_name['cell_type'].fields.append(
  _DATAROW_DATACELL.fields_by_name['bool_t'])
_DATAROW_DATACELL.fields_by_name['bool_t'].containing_oneof = _DATAROW_DATACELL.oneofs_by_name['cell_type']
_DATAROW.fields_by_name['cells'].message_type = _DATAROW_DATACELL
DESCRIPTOR.message_types_by_name['Meta'] = _META
DESCRIPTOR.message_types_by_name['DataRow'] = _DATAROW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Meta = _reflection.GeneratedProtocolMessageType('Meta', (_message.Message,), dict(
  DESCRIPTOR = _META,
  __module__ = 'genericV1_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.Meta)
  ))
_sym_db.RegisterMessage(Meta)

DataRow = _reflection.GeneratedProtocolMessageType('DataRow', (_message.Message,), dict(

  DataCell = _reflection.GeneratedProtocolMessageType('DataCell', (_message.Message,), dict(
    DESCRIPTOR = _DATAROW_DATACELL,
    __module__ = 'genericV1_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.DataRow.DataCell)
    ))
  ,
  DESCRIPTOR = _DATAROW,
  __module__ = 'genericV1_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.DataRow)
  ))
_sym_db.RegisterMessage(DataRow)
_sym_db.RegisterMessage(DataRow.DataCell)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
