// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: datasetV1.proto

package de.uni_passau.fim.padas.padre.api.converter.protobuf;

public final class DatasetV1Protos {
  private DatasetV1Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DataFrameMetaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.DataFrameMeta)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string headers = 1;</code>
     */
    java.util.List<java.lang.String>
        getHeadersList();
    /**
     * <code>repeated string headers = 1;</code>
     */
    int getHeadersCount();
    /**
     * <code>repeated string headers = 1;</code>
     */
    java.lang.String getHeaders(int index);
    /**
     * <code>repeated string headers = 1;</code>
     */
    com.google.protobuf.ByteString
        getHeadersBytes(int index);
  }
  /**
   * Protobuf type {@code protobuf.DataFrameMeta}
   */
  public  static final class DataFrameMeta extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.DataFrameMeta)
      DataFrameMetaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFrameMeta.newBuilder() to construct.
    private DataFrameMeta(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFrameMeta() {
      headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataFrameMeta(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                headers_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              headers_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          headers_ = headers_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameMeta_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameMeta_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.class, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.Builder.class);
    }

    public static final int HEADERS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList headers_;
    /**
     * <code>repeated string headers = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getHeadersList() {
      return headers_;
    }
    /**
     * <code>repeated string headers = 1;</code>
     */
    public int getHeadersCount() {
      return headers_.size();
    }
    /**
     * <code>repeated string headers = 1;</code>
     */
    public java.lang.String getHeaders(int index) {
      return headers_.get(index);
    }
    /**
     * <code>repeated string headers = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHeadersBytes(int index) {
      return headers_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < headers_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, headers_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < headers_.size(); i++) {
          dataSize += computeStringSizeNoTag(headers_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getHeadersList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta)) {
        return super.equals(obj);
      }
      de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta other = (de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta) obj;

      boolean result = true;
      result = result && getHeadersList()
          .equals(other.getHeadersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getHeadersCount() > 0) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + getHeadersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.DataFrameMeta}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.DataFrameMeta)
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMetaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameMeta_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameMeta_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.class, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.Builder.class);
      }

      // Construct using de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameMeta_descriptor;
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta getDefaultInstanceForType() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.getDefaultInstance();
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta build() {
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta buildPartial() {
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta result = new de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          headers_ = headers_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.headers_ = headers_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta) {
          return mergeFrom((de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta other) {
        if (other == de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta.getDefaultInstance()) return this;
        if (!other.headers_.isEmpty()) {
          if (headers_.isEmpty()) {
            headers_ = other.headers_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHeadersIsMutable();
            headers_.addAll(other.headers_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureHeadersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          headers_ = new com.google.protobuf.LazyStringArrayList(headers_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getHeadersList() {
        return headers_.getUnmodifiableView();
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public int getHeadersCount() {
        return headers_.size();
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public java.lang.String getHeaders(int index) {
        return headers_.get(index);
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHeadersBytes(int index) {
        return headers_.getByteString(index);
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public Builder setHeaders(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadersIsMutable();
        headers_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public Builder addHeaders(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public Builder addAllHeaders(
          java.lang.Iterable<java.lang.String> values) {
        ensureHeadersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, headers_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public Builder clearHeaders() {
        headers_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string headers = 1;</code>
       */
      public Builder addHeadersBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureHeadersIsMutable();
        headers_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.DataFrameMeta)
    }

    // @@protoc_insertion_point(class_scope:protobuf.DataFrameMeta)
    private static final de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta();
    }

    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataFrameMeta>
        PARSER = new com.google.protobuf.AbstractParser<DataFrameMeta>() {
      public DataFrameMeta parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataFrameMeta(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataFrameMeta> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataFrameMeta> getParserForType() {
      return PARSER;
    }

    public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameMeta getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataFrameRowOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.DataFrameRow)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    java.util.List<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell> 
        getCellsList();
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell getCells(int index);
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    int getCellsCount();
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    java.util.List<? extends de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder> 
        getCellsOrBuilderList();
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder getCellsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code protobuf.DataFrameRow}
   */
  public  static final class DataFrameRow extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.DataFrameRow)
      DataFrameRowOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DataFrameRow.newBuilder() to construct.
    private DataFrameRow(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataFrameRow() {
      cells_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DataFrameRow(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                cells_ = new java.util.ArrayList<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell>();
                mutable_bitField0_ |= 0x00000001;
              }
              cells_.add(
                  input.readMessage(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          cells_ = java.util.Collections.unmodifiableList(cells_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.class, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.Builder.class);
    }

    public interface DataFrameCellOrBuilder extends
        // @@protoc_insertion_point(interface_extends:protobuf.DataFrameRow.DataFrameCell)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * int		int
       * </pre>
       *
       * <code>int32 int32_t = 1;</code>
       */
      int getInt32T();

      /**
       * <pre>
       * long		int/long
       * </pre>
       *
       * <code>int64 int64_t = 2;</code>
       */
      long getInt64T();

      /**
       * <pre>
       * double	float
       * </pre>
       *
       * <code>double double_t = 3;</code>
       */
      double getDoubleT();

      /**
       * <pre>
       * float	float
       * </pre>
       *
       * <code>float float_t = 4;</code>
       */
      float getFloatT();

      /**
       * <pre>
       * String	str/unicode
       * </pre>
       *
       * <code>string string_t = 5;</code>
       */
      java.lang.String getStringT();
      /**
       * <pre>
       * String	str/unicode
       * </pre>
       *
       * <code>string string_t = 5;</code>
       */
      com.google.protobuf.ByteString
          getStringTBytes();

      /**
       * <pre>
       * boolean	bool
       * </pre>
       *
       * <code>bool bool_t = 6;</code>
       */
      boolean getBoolT();

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.CellTypeCase getCellTypeCase();
    }
    /**
     * Protobuf type {@code protobuf.DataFrameRow.DataFrameCell}
     */
    public  static final class DataFrameCell extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:protobuf.DataFrameRow.DataFrameCell)
        DataFrameCellOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DataFrameCell.newBuilder() to construct.
      private DataFrameCell(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DataFrameCell() {
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private DataFrameCell(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                cellTypeCase_ = 1;
                cellType_ = input.readInt32();
                break;
              }
              case 16: {
                cellTypeCase_ = 2;
                cellType_ = input.readInt64();
                break;
              }
              case 25: {
                cellTypeCase_ = 3;
                cellType_ = input.readDouble();
                break;
              }
              case 37: {
                cellTypeCase_ = 4;
                cellType_ = input.readFloat();
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                cellTypeCase_ = 5;
                cellType_ = s;
                break;
              }
              case 48: {
                cellTypeCase_ = 6;
                cellType_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_DataFrameCell_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_DataFrameCell_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.class, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder.class);
      }

      private int cellTypeCase_ = 0;
      private java.lang.Object cellType_;
      public enum CellTypeCase
          implements com.google.protobuf.Internal.EnumLite {
        INT32_T(1),
        INT64_T(2),
        DOUBLE_T(3),
        FLOAT_T(4),
        STRING_T(5),
        BOOL_T(6),
        CELLTYPE_NOT_SET(0);
        private final int value;
        private CellTypeCase(int value) {
          this.value = value;
        }
        /**
         * @deprecated Use {@link #forNumber(int)} instead.
         */
        @java.lang.Deprecated
        public static CellTypeCase valueOf(int value) {
          return forNumber(value);
        }

        public static CellTypeCase forNumber(int value) {
          switch (value) {
            case 1: return INT32_T;
            case 2: return INT64_T;
            case 3: return DOUBLE_T;
            case 4: return FLOAT_T;
            case 5: return STRING_T;
            case 6: return BOOL_T;
            case 0: return CELLTYPE_NOT_SET;
            default: return null;
          }
        }
        public int getNumber() {
          return this.value;
        }
      };

      public CellTypeCase
      getCellTypeCase() {
        return CellTypeCase.forNumber(
            cellTypeCase_);
      }

      public static final int INT32_T_FIELD_NUMBER = 1;
      /**
       * <pre>
       * int		int
       * </pre>
       *
       * <code>int32 int32_t = 1;</code>
       */
      public int getInt32T() {
        if (cellTypeCase_ == 1) {
          return (java.lang.Integer) cellType_;
        }
        return 0;
      }

      public static final int INT64_T_FIELD_NUMBER = 2;
      /**
       * <pre>
       * long		int/long
       * </pre>
       *
       * <code>int64 int64_t = 2;</code>
       */
      public long getInt64T() {
        if (cellTypeCase_ == 2) {
          return (java.lang.Long) cellType_;
        }
        return 0L;
      }

      public static final int DOUBLE_T_FIELD_NUMBER = 3;
      /**
       * <pre>
       * double	float
       * </pre>
       *
       * <code>double double_t = 3;</code>
       */
      public double getDoubleT() {
        if (cellTypeCase_ == 3) {
          return (java.lang.Double) cellType_;
        }
        return 0D;
      }

      public static final int FLOAT_T_FIELD_NUMBER = 4;
      /**
       * <pre>
       * float	float
       * </pre>
       *
       * <code>float float_t = 4;</code>
       */
      public float getFloatT() {
        if (cellTypeCase_ == 4) {
          return (java.lang.Float) cellType_;
        }
        return 0F;
      }

      public static final int STRING_T_FIELD_NUMBER = 5;
      /**
       * <pre>
       * String	str/unicode
       * </pre>
       *
       * <code>string string_t = 5;</code>
       */
      public java.lang.String getStringT() {
        java.lang.Object ref = "";
        if (cellTypeCase_ == 5) {
          ref = cellType_;
        }
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (cellTypeCase_ == 5) {
            cellType_ = s;
          }
          return s;
        }
      }
      /**
       * <pre>
       * String	str/unicode
       * </pre>
       *
       * <code>string string_t = 5;</code>
       */
      public com.google.protobuf.ByteString
          getStringTBytes() {
        java.lang.Object ref = "";
        if (cellTypeCase_ == 5) {
          ref = cellType_;
        }
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (cellTypeCase_ == 5) {
            cellType_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int BOOL_T_FIELD_NUMBER = 6;
      /**
       * <pre>
       * boolean	bool
       * </pre>
       *
       * <code>bool bool_t = 6;</code>
       */
      public boolean getBoolT() {
        if (cellTypeCase_ == 6) {
          return (java.lang.Boolean) cellType_;
        }
        return false;
      }

      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (cellTypeCase_ == 1) {
          output.writeInt32(
              1, (int)((java.lang.Integer) cellType_));
        }
        if (cellTypeCase_ == 2) {
          output.writeInt64(
              2, (long)((java.lang.Long) cellType_));
        }
        if (cellTypeCase_ == 3) {
          output.writeDouble(
              3, (double)((java.lang.Double) cellType_));
        }
        if (cellTypeCase_ == 4) {
          output.writeFloat(
              4, (float)((java.lang.Float) cellType_));
        }
        if (cellTypeCase_ == 5) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, cellType_);
        }
        if (cellTypeCase_ == 6) {
          output.writeBool(
              6, (boolean)((java.lang.Boolean) cellType_));
        }
        unknownFields.writeTo(output);
      }

      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (cellTypeCase_ == 1) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(
                1, (int)((java.lang.Integer) cellType_));
        }
        if (cellTypeCase_ == 2) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(
                2, (long)((java.lang.Long) cellType_));
        }
        if (cellTypeCase_ == 3) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(
                3, (double)((java.lang.Double) cellType_));
        }
        if (cellTypeCase_ == 4) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(
                4, (float)((java.lang.Float) cellType_));
        }
        if (cellTypeCase_ == 5) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, cellType_);
        }
        if (cellTypeCase_ == 6) {
          size += com.google.protobuf.CodedOutputStream
            .computeBoolSize(
                6, (boolean)((java.lang.Boolean) cellType_));
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell)) {
          return super.equals(obj);
        }
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell other = (de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell) obj;

        boolean result = true;
        result = result && getCellTypeCase().equals(
            other.getCellTypeCase());
        if (!result) return false;
        switch (cellTypeCase_) {
          case 1:
            result = result && (getInt32T()
                == other.getInt32T());
            break;
          case 2:
            result = result && (getInt64T()
                == other.getInt64T());
            break;
          case 3:
            result = result && (
                java.lang.Double.doubleToLongBits(getDoubleT())
                == java.lang.Double.doubleToLongBits(
                    other.getDoubleT()));
            break;
          case 4:
            result = result && (
                java.lang.Float.floatToIntBits(getFloatT())
                == java.lang.Float.floatToIntBits(
                    other.getFloatT()));
            break;
          case 5:
            result = result && getStringT()
                .equals(other.getStringT());
            break;
          case 6:
            result = result && (getBoolT()
                == other.getBoolT());
            break;
          case 0:
          default:
        }
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        switch (cellTypeCase_) {
          case 1:
            hash = (37 * hash) + INT32_T_FIELD_NUMBER;
            hash = (53 * hash) + getInt32T();
            break;
          case 2:
            hash = (37 * hash) + INT64_T_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getInt64T());
            break;
          case 3:
            hash = (37 * hash) + DOUBLE_T_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getDoubleT()));
            break;
          case 4:
            hash = (37 * hash) + FLOAT_T_FIELD_NUMBER;
            hash = (53 * hash) + java.lang.Float.floatToIntBits(
                getFloatT());
            break;
          case 5:
            hash = (37 * hash) + STRING_T_FIELD_NUMBER;
            hash = (53 * hash) + getStringT().hashCode();
            break;
          case 6:
            hash = (37 * hash) + BOOL_T_FIELD_NUMBER;
            hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
                getBoolT());
            break;
          case 0:
          default:
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code protobuf.DataFrameRow.DataFrameCell}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:protobuf.DataFrameRow.DataFrameCell)
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_DataFrameCell_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_DataFrameCell_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.class, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder.class);
        }

        // Construct using de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        public Builder clear() {
          super.clear();
          cellTypeCase_ = 0;
          cellType_ = null;
          return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_DataFrameCell_descriptor;
        }

        public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell getDefaultInstanceForType() {
          return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.getDefaultInstance();
        }

        public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell build() {
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell buildPartial() {
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell result = new de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell(this);
          if (cellTypeCase_ == 1) {
            result.cellType_ = cellType_;
          }
          if (cellTypeCase_ == 2) {
            result.cellType_ = cellType_;
          }
          if (cellTypeCase_ == 3) {
            result.cellType_ = cellType_;
          }
          if (cellTypeCase_ == 4) {
            result.cellType_ = cellType_;
          }
          if (cellTypeCase_ == 5) {
            result.cellType_ = cellType_;
          }
          if (cellTypeCase_ == 6) {
            result.cellType_ = cellType_;
          }
          result.cellTypeCase_ = cellTypeCase_;
          onBuilt();
          return result;
        }

        public Builder clone() {
          return (Builder) super.clone();
        }
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell) {
            return mergeFrom((de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell other) {
          if (other == de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.getDefaultInstance()) return this;
          switch (other.getCellTypeCase()) {
            case INT32_T: {
              setInt32T(other.getInt32T());
              break;
            }
            case INT64_T: {
              setInt64T(other.getInt64T());
              break;
            }
            case DOUBLE_T: {
              setDoubleT(other.getDoubleT());
              break;
            }
            case FLOAT_T: {
              setFloatT(other.getFloatT());
              break;
            }
            case STRING_T: {
              cellTypeCase_ = 5;
              cellType_ = other.cellType_;
              onChanged();
              break;
            }
            case BOOL_T: {
              setBoolT(other.getBoolT());
              break;
            }
            case CELLTYPE_NOT_SET: {
              break;
            }
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int cellTypeCase_ = 0;
        private java.lang.Object cellType_;
        public CellTypeCase
            getCellTypeCase() {
          return CellTypeCase.forNumber(
              cellTypeCase_);
        }

        public Builder clearCellType() {
          cellTypeCase_ = 0;
          cellType_ = null;
          onChanged();
          return this;
        }


        /**
         * <pre>
         * int		int
         * </pre>
         *
         * <code>int32 int32_t = 1;</code>
         */
        public int getInt32T() {
          if (cellTypeCase_ == 1) {
            return (java.lang.Integer) cellType_;
          }
          return 0;
        }
        /**
         * <pre>
         * int		int
         * </pre>
         *
         * <code>int32 int32_t = 1;</code>
         */
        public Builder setInt32T(int value) {
          cellTypeCase_ = 1;
          cellType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * int		int
         * </pre>
         *
         * <code>int32 int32_t = 1;</code>
         */
        public Builder clearInt32T() {
          if (cellTypeCase_ == 1) {
            cellTypeCase_ = 0;
            cellType_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <pre>
         * long		int/long
         * </pre>
         *
         * <code>int64 int64_t = 2;</code>
         */
        public long getInt64T() {
          if (cellTypeCase_ == 2) {
            return (java.lang.Long) cellType_;
          }
          return 0L;
        }
        /**
         * <pre>
         * long		int/long
         * </pre>
         *
         * <code>int64 int64_t = 2;</code>
         */
        public Builder setInt64T(long value) {
          cellTypeCase_ = 2;
          cellType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * long		int/long
         * </pre>
         *
         * <code>int64 int64_t = 2;</code>
         */
        public Builder clearInt64T() {
          if (cellTypeCase_ == 2) {
            cellTypeCase_ = 0;
            cellType_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <pre>
         * double	float
         * </pre>
         *
         * <code>double double_t = 3;</code>
         */
        public double getDoubleT() {
          if (cellTypeCase_ == 3) {
            return (java.lang.Double) cellType_;
          }
          return 0D;
        }
        /**
         * <pre>
         * double	float
         * </pre>
         *
         * <code>double double_t = 3;</code>
         */
        public Builder setDoubleT(double value) {
          cellTypeCase_ = 3;
          cellType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * double	float
         * </pre>
         *
         * <code>double double_t = 3;</code>
         */
        public Builder clearDoubleT() {
          if (cellTypeCase_ == 3) {
            cellTypeCase_ = 0;
            cellType_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <pre>
         * float	float
         * </pre>
         *
         * <code>float float_t = 4;</code>
         */
        public float getFloatT() {
          if (cellTypeCase_ == 4) {
            return (java.lang.Float) cellType_;
          }
          return 0F;
        }
        /**
         * <pre>
         * float	float
         * </pre>
         *
         * <code>float float_t = 4;</code>
         */
        public Builder setFloatT(float value) {
          cellTypeCase_ = 4;
          cellType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * float	float
         * </pre>
         *
         * <code>float float_t = 4;</code>
         */
        public Builder clearFloatT() {
          if (cellTypeCase_ == 4) {
            cellTypeCase_ = 0;
            cellType_ = null;
            onChanged();
          }
          return this;
        }

        /**
         * <pre>
         * String	str/unicode
         * </pre>
         *
         * <code>string string_t = 5;</code>
         */
        public java.lang.String getStringT() {
          java.lang.Object ref = "";
          if (cellTypeCase_ == 5) {
            ref = cellType_;
          }
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (cellTypeCase_ == 5) {
              cellType_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * String	str/unicode
         * </pre>
         *
         * <code>string string_t = 5;</code>
         */
        public com.google.protobuf.ByteString
            getStringTBytes() {
          java.lang.Object ref = "";
          if (cellTypeCase_ == 5) {
            ref = cellType_;
          }
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            if (cellTypeCase_ == 5) {
              cellType_ = b;
            }
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * String	str/unicode
         * </pre>
         *
         * <code>string string_t = 5;</code>
         */
        public Builder setStringT(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  cellTypeCase_ = 5;
          cellType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * String	str/unicode
         * </pre>
         *
         * <code>string string_t = 5;</code>
         */
        public Builder clearStringT() {
          if (cellTypeCase_ == 5) {
            cellTypeCase_ = 0;
            cellType_ = null;
            onChanged();
          }
          return this;
        }
        /**
         * <pre>
         * String	str/unicode
         * </pre>
         *
         * <code>string string_t = 5;</code>
         */
        public Builder setStringTBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          cellTypeCase_ = 5;
          cellType_ = value;
          onChanged();
          return this;
        }

        /**
         * <pre>
         * boolean	bool
         * </pre>
         *
         * <code>bool bool_t = 6;</code>
         */
        public boolean getBoolT() {
          if (cellTypeCase_ == 6) {
            return (java.lang.Boolean) cellType_;
          }
          return false;
        }
        /**
         * <pre>
         * boolean	bool
         * </pre>
         *
         * <code>bool bool_t = 6;</code>
         */
        public Builder setBoolT(boolean value) {
          cellTypeCase_ = 6;
          cellType_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * boolean	bool
         * </pre>
         *
         * <code>bool bool_t = 6;</code>
         */
        public Builder clearBoolT() {
          if (cellTypeCase_ == 6) {
            cellTypeCase_ = 0;
            cellType_ = null;
            onChanged();
          }
          return this;
        }
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:protobuf.DataFrameRow.DataFrameCell)
      }

      // @@protoc_insertion_point(class_scope:protobuf.DataFrameRow.DataFrameCell)
      private static final de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell();
      }

      public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DataFrameCell>
          PARSER = new com.google.protobuf.AbstractParser<DataFrameCell>() {
        public DataFrameCell parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataFrameCell(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DataFrameCell> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DataFrameCell> getParserForType() {
        return PARSER;
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int CELLS_FIELD_NUMBER = 1;
    private java.util.List<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell> cells_;
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    public java.util.List<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell> getCellsList() {
      return cells_;
    }
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    public java.util.List<? extends de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder> 
        getCellsOrBuilderList() {
      return cells_;
    }
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    public int getCellsCount() {
      return cells_.size();
    }
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell getCells(int index) {
      return cells_.get(index);
    }
    /**
     * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
     */
    public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder getCellsOrBuilder(
        int index) {
      return cells_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < cells_.size(); i++) {
        output.writeMessage(1, cells_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < cells_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, cells_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow)) {
        return super.equals(obj);
      }
      de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow other = (de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow) obj;

      boolean result = true;
      result = result && getCellsList()
          .equals(other.getCellsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getCellsCount() > 0) {
        hash = (37 * hash) + CELLS_FIELD_NUMBER;
        hash = (53 * hash) + getCellsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.DataFrameRow}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.DataFrameRow)
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRowOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.class, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.Builder.class);
      }

      // Construct using de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCellsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.internal_static_protobuf_DataFrameRow_descriptor;
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow getDefaultInstanceForType() {
        return de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.getDefaultInstance();
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow build() {
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow buildPartial() {
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow result = new de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow(this);
        int from_bitField0_ = bitField0_;
        if (cellsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            cells_ = java.util.Collections.unmodifiableList(cells_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.cells_ = cells_;
        } else {
          result.cells_ = cellsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow) {
          return mergeFrom((de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow other) {
        if (other == de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.getDefaultInstance()) return this;
        if (cellsBuilder_ == null) {
          if (!other.cells_.isEmpty()) {
            if (cells_.isEmpty()) {
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureCellsIsMutable();
              cells_.addAll(other.cells_);
            }
            onChanged();
          }
        } else {
          if (!other.cells_.isEmpty()) {
            if (cellsBuilder_.isEmpty()) {
              cellsBuilder_.dispose();
              cellsBuilder_ = null;
              cells_ = other.cells_;
              bitField0_ = (bitField0_ & ~0x00000001);
              cellsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCellsFieldBuilder() : null;
            } else {
              cellsBuilder_.addAllMessages(other.cells_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell> cells_ =
        java.util.Collections.emptyList();
      private void ensureCellsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          cells_ = new java.util.ArrayList<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell>(cells_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder> cellsBuilder_;

      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public java.util.List<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell> getCellsList() {
        if (cellsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(cells_);
        } else {
          return cellsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public int getCellsCount() {
        if (cellsBuilder_ == null) {
          return cells_.size();
        } else {
          return cellsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell getCells(int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);
        } else {
          return cellsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder setCells(
          int index, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.set(index, value);
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder setCells(
          int index, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.set(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder addCells(de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder addCells(
          int index, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell value) {
        if (cellsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCellsIsMutable();
          cells_.add(index, value);
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder addCells(
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder addCells(
          int index, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder builderForValue) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.add(index, builderForValue.build());
          onChanged();
        } else {
          cellsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder addAllCells(
          java.lang.Iterable<? extends de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell> values) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, cells_);
          onChanged();
        } else {
          cellsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder clearCells() {
        if (cellsBuilder_ == null) {
          cells_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          cellsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public Builder removeCells(int index) {
        if (cellsBuilder_ == null) {
          ensureCellsIsMutable();
          cells_.remove(index);
          onChanged();
        } else {
          cellsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder getCellsBuilder(
          int index) {
        return getCellsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder getCellsOrBuilder(
          int index) {
        if (cellsBuilder_ == null) {
          return cells_.get(index);  } else {
          return cellsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public java.util.List<? extends de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder> 
           getCellsOrBuilderList() {
        if (cellsBuilder_ != null) {
          return cellsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(cells_);
        }
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder addCellsBuilder() {
        return getCellsFieldBuilder().addBuilder(
            de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder addCellsBuilder(
          int index) {
        return getCellsFieldBuilder().addBuilder(
            index, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.getDefaultInstance());
      }
      /**
       * <code>repeated .protobuf.DataFrameRow.DataFrameCell cells = 1;</code>
       */
      public java.util.List<de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder> 
           getCellsBuilderList() {
        return getCellsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder> 
          getCellsFieldBuilder() {
        if (cellsBuilder_ == null) {
          cellsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCell.Builder, de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow.DataFrameCellOrBuilder>(
                  cells_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          cells_ = null;
        }
        return cellsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.DataFrameRow)
    }

    // @@protoc_insertion_point(class_scope:protobuf.DataFrameRow)
    private static final de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow();
    }

    public static de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataFrameRow>
        PARSER = new com.google.protobuf.AbstractParser<DataFrameRow>() {
      public DataFrameRow parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DataFrameRow(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataFrameRow> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataFrameRow> getParserForType() {
      return PARSER;
    }

    public de.uni_passau.fim.padas.padre.api.converter.protobuf.DatasetV1Protos.DataFrameRow getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DataFrameMeta_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_DataFrameMeta_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DataFrameRow_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_DataFrameRow_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_DataFrameRow_DataFrameCell_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_DataFrameRow_DataFrameCell_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017datasetV1.proto\022\010protobuf\" \n\rDataFrame" +
      "Meta\022\017\n\007headers\030\001 \003(\t\"\325\001\n\014DataFrameRow\0223" +
      "\n\005cells\030\001 \003(\0132$.protobuf.DataFrameRow.Da" +
      "taFrameCell\032\217\001\n\rDataFrameCell\022\021\n\007int32_t" +
      "\030\001 \001(\005H\000\022\021\n\007int64_t\030\002 \001(\003H\000\022\022\n\010double_t\030" +
      "\003 \001(\001H\000\022\021\n\007float_t\030\004 \001(\002H\000\022\022\n\010string_t\030\005" +
      " \001(\tH\000\022\020\n\006bool_t\030\006 \001(\010H\000B\013\n\tcell_typeBG\n" +
      "4de.uni_passau.fim.padas.padre.api.conve" +
      "rter.protobufB\017DatasetV1Protosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protobuf_DataFrameMeta_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_DataFrameMeta_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_DataFrameMeta_descriptor,
        new java.lang.String[] { "Headers", });
    internal_static_protobuf_DataFrameRow_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protobuf_DataFrameRow_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_DataFrameRow_descriptor,
        new java.lang.String[] { "Cells", });
    internal_static_protobuf_DataFrameRow_DataFrameCell_descriptor =
      internal_static_protobuf_DataFrameRow_descriptor.getNestedTypes().get(0);
    internal_static_protobuf_DataFrameRow_DataFrameCell_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_DataFrameRow_DataFrameCell_descriptor,
        new java.lang.String[] { "Int32T", "Int64T", "DoubleT", "FloatT", "StringT", "BoolT", "CellType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
