# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resultV1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resultV1.proto',
  package='protobuf',
  syntax='proto3',
  serialized_pb=_b('\n\x0eresultV1.proto\x12\x08protobuf\"\x88\x02\n\x0bResultEntry\x12\r\n\x05index\x18\x01 \x01(\x03\x12/\n\nprediction\x18\x02 \x03(\x0b\x32\x1b.protobuf.ResultEntry.Value\x12*\n\x05truth\x18\x03 \x03(\x0b\x32\x1b.protobuf.ResultEntry.Value\x12*\n\x05score\x18\x04 \x03(\x0b\x32\x1b.protobuf.ResultEntry.Value\x1a\x61\n\x05Value\x12\x11\n\x07int32_t\x18\x01 \x01(\x05H\x00\x12\x11\n\x07int64_t\x18\x02 \x01(\x03H\x00\x12\x12\n\x08\x64ouble_t\x18\x03 \x01(\x01H\x00\x12\x11\n\x07\x66loat_t\x18\x04 \x01(\x02H\x00\x42\x0b\n\tcell_typeBM\n;de.uni_passau.fim.padas.padre.api.converter.binary.protobufB\x0eResultV1Protosb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_RESULTENTRY_VALUE = _descriptor.Descriptor(
  name='Value',
  full_name='protobuf.ResultEntry.Value',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='int32_t', full_name='protobuf.ResultEntry.Value.int32_t', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='int64_t', full_name='protobuf.ResultEntry.Value.int64_t', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='double_t', full_name='protobuf.ResultEntry.Value.double_t', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='float_t', full_name='protobuf.ResultEntry.Value.float_t', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='cell_type', full_name='protobuf.ResultEntry.Value.cell_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=196,
  serialized_end=293,
)

_RESULTENTRY = _descriptor.Descriptor(
  name='ResultEntry',
  full_name='protobuf.ResultEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='protobuf.ResultEntry.index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prediction', full_name='protobuf.ResultEntry.prediction', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='truth', full_name='protobuf.ResultEntry.truth', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='score', full_name='protobuf.ResultEntry.score', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_RESULTENTRY_VALUE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=293,
)

_RESULTENTRY_VALUE.containing_type = _RESULTENTRY
_RESULTENTRY_VALUE.oneofs_by_name['cell_type'].fields.append(
  _RESULTENTRY_VALUE.fields_by_name['int32_t'])
_RESULTENTRY_VALUE.fields_by_name['int32_t'].containing_oneof = _RESULTENTRY_VALUE.oneofs_by_name['cell_type']
_RESULTENTRY_VALUE.oneofs_by_name['cell_type'].fields.append(
  _RESULTENTRY_VALUE.fields_by_name['int64_t'])
_RESULTENTRY_VALUE.fields_by_name['int64_t'].containing_oneof = _RESULTENTRY_VALUE.oneofs_by_name['cell_type']
_RESULTENTRY_VALUE.oneofs_by_name['cell_type'].fields.append(
  _RESULTENTRY_VALUE.fields_by_name['double_t'])
_RESULTENTRY_VALUE.fields_by_name['double_t'].containing_oneof = _RESULTENTRY_VALUE.oneofs_by_name['cell_type']
_RESULTENTRY_VALUE.oneofs_by_name['cell_type'].fields.append(
  _RESULTENTRY_VALUE.fields_by_name['float_t'])
_RESULTENTRY_VALUE.fields_by_name['float_t'].containing_oneof = _RESULTENTRY_VALUE.oneofs_by_name['cell_type']
_RESULTENTRY.fields_by_name['prediction'].message_type = _RESULTENTRY_VALUE
_RESULTENTRY.fields_by_name['truth'].message_type = _RESULTENTRY_VALUE
_RESULTENTRY.fields_by_name['score'].message_type = _RESULTENTRY_VALUE
DESCRIPTOR.message_types_by_name['ResultEntry'] = _RESULTENTRY

ResultEntry = _reflection.GeneratedProtocolMessageType('ResultEntry', (_message.Message,), dict(

  Value = _reflection.GeneratedProtocolMessageType('Value', (_message.Message,), dict(
    DESCRIPTOR = _RESULTENTRY_VALUE,
    __module__ = 'resultV1_pb2'
    # @@protoc_insertion_point(class_scope:protobuf.ResultEntry.Value)
    ))
  ,
  DESCRIPTOR = _RESULTENTRY,
  __module__ = 'resultV1_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.ResultEntry)
  ))
_sym_db.RegisterMessage(ResultEntry)
_sym_db.RegisterMessage(ResultEntry.Value)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n;de.uni_passau.fim.padas.padre.api.converter.binary.protobufB\016ResultV1Protos'))
# @@protoc_insertion_point(module_scope)
